__author__ = "xiaonan"

"""
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def main():
	x = 1
	y = 2
	sum = 0

	while x <= 4000000 and y <= 4000000:
		if x % 2 == 0:
			sum += x
		if y % 2 == 0:
			sum += y
		x += y
		y += x
	print sum


if __name__ == '__main__':
	main()