__author__ = "xiaonan"

"""
Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from math import sqrt

def triangular_number(nth):
	result = int(0.5 * nth * (nth + 1))
	return result


def count_divisors(number):
	result = 2
	for i in xrange(2, int(sqrt(number)) + 1):
		if ((number % i) == 0):
			if (i != sqrt(number)):
				result += 2
			else:
				result += 1
	return result


def main():
	i = 0
	num = 1
	while count_divisors(num) <= 500:
		num = triangular_number(i)
		i += 1
	print num


if __name__ == '__main__':
	main()